/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tomemu;

import javax.microedition.lcdui.Display;
import javax.microedition.lcdui.Displayable;
import javax.microedition.midlet.MIDlet;
import javax.microedition.midlet.MIDletStateChangeException;
import javax.swing.*;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * @author Solkin
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new MidletPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }

            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel1MouseReleased(evt);
            }
        });
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.setLayout(new java.awt.GridLayout(1, 1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(240, 320));

        jPanel2.setLayout(new java.awt.GridLayout(4, 3, 2, 2));

        jButton1.setText("1");
        jButton1.addActionListener(e -> emulateKeyPressed(49));
        jPanel2.add(jButton1);

        jButton2.setText("2");
        jButton2.addActionListener(e -> emulateKeyPressed(50));
        jPanel2.add(jButton2);

        jButton3.setText("3");
        jButton3.addActionListener(e -> emulateKeyPressed(51));
        jPanel2.add(jButton3);

        jButton4.setText("4");
        jButton4.addActionListener(e -> emulateKeyPressed(52));
        jPanel2.add(jButton4);

        jButton5.setText("5");
        jButton5.addActionListener(e -> emulateKeyPressed(53));
        jPanel2.add(jButton5);

        jButton6.setText("6");
        jButton6.addActionListener(e -> emulateKeyPressed(54));
        jPanel2.add(jButton6);

        jButton7.setText("7");
        jButton7.addActionListener(e -> emulateKeyPressed(55));
        jPanel2.add(jButton7);

        jButton8.setText("8");
        jButton8.addActionListener(e -> emulateKeyPressed(56));
        jPanel2.add(jButton8);

        jButton9.setText("9");
        jButton9.addActionListener(e -> emulateKeyPressed(57));
        jPanel2.add(jButton9);

        jButton10.setText("*");
        jButton10.addActionListener(e -> emulateKeyPressed(42));
        jPanel2.add(jButton10);

        jButton11.setText("0");
        jButton11.addActionListener(e -> emulateKeyPressed(48));
        jPanel2.add(jButton11);

        jButton12.setText("#");
        jButton12.addActionListener(e -> emulateKeyPressed(35));
        jPanel2.add(jButton12);

        jPanel3.setLayout(new java.awt.BorderLayout(2, 2));
        jButton13.setText("o");
        jButton13.addActionListener(e -> emulateKeyPressed(8));
        jPanel3.add(jButton13, java.awt.BorderLayout.CENTER);

        jButton14.setText("<");
        jButton14.addActionListener(e -> emulateKeyPressed(2));
        jPanel3.add(jButton14, java.awt.BorderLayout.LINE_START);

        jButton15.setText(">");
        jButton15.addActionListener(e -> emulateKeyPressed(5));
        jPanel3.add(jButton15, java.awt.BorderLayout.LINE_END);

        jButton16.setText("^");
        jButton16.addActionListener(e -> emulateKeyPressed(1));
        jPanel3.add(jButton16, java.awt.BorderLayout.PAGE_START);

        jButton17.setText("v");
        jButton17.addActionListener(e -> emulateKeyPressed(6));
        jPanel3.add(jButton17, java.awt.BorderLayout.PAGE_END);

        jPanel4.setLayout(new java.awt.BorderLayout());
        jButton18.setText("Left");
        jButton18.addActionListener(e -> emulateKeyPressed(1000001));
        jPanel4.add(jButton18, java.awt.BorderLayout.LINE_START);

        jButton19.setText("Right");
        jButton19.addActionListener(e -> emulateKeyPressed(1000002));
        jPanel4.add(jButton19, java.awt.BorderLayout.LINE_END);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emulateKeyPressed(int keyCode) {
        Display.keyPressed(keyCode);
        Display.keyReleased(keyCode);
    }

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        Display.pointerPressed(evt.getX(), evt.getY());
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseReleased
        Display.pointerReleased(evt.getX(), evt.getY());
    }//GEN-LAST:event_jPanel1MouseReleased

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        Display.pointerDragged(evt.getX(), evt.getY());
    }//GEN-LAST:event_jPanel1MouseDragged

    public void initEmulator() {
        /** Starting midlet **/
        MIDlet midlet = new debug.MidletMain();
        try {
            midlet.startApp();
        } catch (MIDletStateChangeException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        Displayable.width = (int) jPanel1.getPreferredSize().getWidth();
        Displayable.height = (int) jPanel1.getPreferredSize().getHeight();
        Display.midletPanel = (MidletPanel) jPanel1;
        Display.getDisplay(midlet).getCurrent().callRepaint();

        System.out.println("width = " + Displayable.width + "; height = " + Displayable.height);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
    /*try {
     for ( javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels() ) {
     if ( "Nimbus".equals( info.getName() ) ) {
     javax.swing.UIManager.setLookAndFeel( info.getClassName() );
     break;
     }
     }
     } catch ( ClassNotFoundException ex ) {
     java.util.logging.Logger.getLogger( MainFrame.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
     } catch ( InstantiationException ex ) {
     java.util.logging.Logger.getLogger( MainFrame.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
     } catch ( IllegalAccessException ex ) {
     java.util.logging.Logger.getLogger( MainFrame.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
     } catch ( javax.swing.UnsupportedLookAndFeelException ex ) {
     java.util.logging.Logger.getLogger( MainFrame.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
     }*/
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (Throwable ex) {
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                MainFrame mainFrame = new MainFrame();
                mainFrame.initEmulator();
                mainFrame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
