package tomemu;

import javax.microedition.lcdui.Canvas;
import javax.microedition.lcdui.Display;
import javax.microedition.lcdui.Displayable;
import java.awt.*;
import java.awt.image.BufferedImage;

/**
 * @author Solkin
 */
public class MidletPanel extends javax.swing.JPanel {

    private javax.microedition.lcdui.Graphics graphics;
    public BufferedImage image;

    /**
     * Creates new form MidletPanel
     */
    public MidletPanel() {
        initComponents();
        image = new BufferedImage(240, 320, BufferedImage.TYPE_INT_RGB);
        graphics = new javax.microedition.lcdui.Graphics(image.getGraphics(), 0, 0);
    }

    @Override
    public void paint(Graphics g) {
        Displayable displayable = Display.display.getCurrent();
        if (displayable instanceof Canvas) {
            ((Canvas) displayable).paintCanvas(graphics);
        }
        g.drawImage(image, 0, 0, null);
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
